Repository sendOwlOrganization/SendOwl-Web, pull requests merged in 2022-04, with the labels that each got.

#1 Board 컴포넌트
  package.json
  src/components/board/Board.tsx
  src/components/board/BoardContent.tsx
  src/components/board/BoardFooter.tsx
  src/components/board/BoardHeader.tsx
  src/components/board/index.ts
  yarn.lock
Labels: enhancement

#2 Storybook 추가
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/stories/board/Board.stories.tsx
  src/stories/board/BoardContent.stories.tsx
  src/stories/board/BoardFooter.stories.tsx
  src/stories/board/BoardHeader.stories.tsx
  yarn.lock
Labels: documentation

#4 EmotionCache 타입 오류
  pages/_app.tsx
Labels: bug, help wanted

#6 로그인 버튼 UI
  package.json
  src/components/login/LoginButton.tsx
  src/components/login/LoginForm.tsx
  src/components/login/index.ts
  src/stories/login/LoginButton.stories.tsx
  src/stories/login/LoginForm.stories.tsx
  yarn.lock
Labels: enhancement

#8 Prettier 추가
  .prettierrc
  package.json
  yarn.lock
Labels: enhancement

#9 회원가입 폼 UI
  src/components/login/LoginForm.tsx
  src/components/sign-up/SignUpForm.tsx
  src/stories/sign-up/SignUpForm.stories.tsx
  src/tools/validation.ts
  src/types/SignUpDto.ts
Labels: enhancement

#5 Main 컴포넌트
  pages/_app.tsx
  public/images/logo.png
  src/components/global/Header.tsx
  src/components/global/Layout.tsx
  src/components/global/index.ts
  src/components/main/Content.tsx
  src/components/main/Main.tsx
  src/components/main/MainContent.tsx
  src/components/main/index.ts
  src/components/search/Search.tsx
  src/components/search/index.ts
Labels: enhancement
